### ISSUE TITLE
Possible bugs detected by Angie

### ISSUE THREAD

**Issue by angieburnett** [serbinsh/SSerbin_etal_2019_NewPhytologist#1]
When running the script via the RPubs version, nComps was not generated automatically (pressDFres not found in the t.test script). I had to manually set nComps <- 14 (guided by the annotation) to move to the next step.

When running the script from GitHub using RStudio, I could see the graphics provided in the Rmd file but running the code chunks didn't generate my own graphics in the graphics window of RStudio. I expected I would see the graphics there.

I tried both of these scripts from GitHub:
run_lma_plsr_example.Rmd
run_lma_plsr_example_neon.Rmd

I also think the uninitiated user would benefit from a bit more description of what the code is doing, throughout.

**Comment by serbinsh** [comment]
@angieburnett You meant to post this [here](https://github.com/TESTgroup-BNL/How_to_PLSR/issues) correct?  This isnt the correct GitHub for the paper script!  I will move this.

**Comment by serbinsh** [comment]
@angieburnett for reference the github you want is here: https://github.com/TESTgroup-BNL/How_to_PLSR
